Issues/399
headwirecom/peregrine-cms pull request #408
Opened 2020-06-03 17:01 UTC by smcgrath0

TO Test: 
check base-page under the templates tab for the themeclean-flex site
Should see a reference list to the pages that uses the template (index, error ...)
![image](https://user-images.githubusercontent.com/49845255/83666020-264a7700-a581-11ea-9933-ed4db0b18829.png)

old PR: #403

2020-06-03 19:33 UTC, GastonGonzalez commented
@smcgrath0  - Please resolve this issue in the console.

```
admin.js:33401 [Vue warn]: Duplicate keys detected: '/content/themecleanflex/pages/page1'. This may cause an update error.

found in

---> <AdminComponentsExplorerpreviewcontent>
       <AdminComponentsTemplateview>
         <AdminComponentsWorkspace>
           <AdminComponentsToolingpage>
             <Root>

admin.js:33401 [Vue warn]: Duplicate keys detected: '/content/themecleanflex/pages/page2'. This may cause an update error.

found in

---> <AdminComponentsExplorerpreviewcontent>
       <AdminComponentsTemplateview>
         <AdminComponentsWorkspace>
           <AdminComponentsToolingpage>
             <Root>
```

1. Create two pages.
1. In the second page add a card component and reference the other page.
2. Check the pages references.

2020-06-04 20:56 UTC, GastonGonzalez commented on admin-base/ui.apps/src/main/js/apiImpl.js
> +            //checks if there is an element next to current element
@smcgrath0, consider this: what happens if the response from '/perapi/admin/refBy.json' does not include the `referencedBy.[]` elements sorted by path? Will this code still work?

2020-06-04 23:39 UTC, GastonGonzalez commented on admin-base/ui.apps/src/main/js/apiImpl.js
> +            //checks if there is an element next to current element
@smcgrath0 and @dna113p - Why can't we use a `map` and make this dead simple? I am no ES6 expert, but here's what I am thinking. 

```
let referencedBy = [
    {
        "name": "carousel",
        "path": "/content/themecleanflex/pages/library/carousel",
        "propertyName": "imagepath",
        "propertyPath": "/content/themecleanflex/pages/library/carousel/jcr:content/container22/carousel9/slides/c6",
    },
    {
        "name": "sample-owl",
        "path": "/content/themecleanflex/pages/library/carousel/sample-owl",
        "propertyName": "imagepath",
        "propertyPath": "/content/themecleanflex/pages/library/carousel/sample-owl/jcr:content/container175/carousel6/slides/c3",
    },
    {
        "name": "sample-owl",
        "path": "/content/themecleanflex/pages/library/carousel/sample-owl",
        "propertyName": "imagepath",
        "propertyPath": "/content/themecleanflex/pages/library/carousel/sample-owl/jcr:content/container175/carousel12/slides/c9",
    },
]

let result = referencedBy.reduce(
    (map => (r, a) => (!map.has(a.path) && map.set(a.path, r[r.push({ name: a.name, path: a.path, propertyName: a.propertyName, propertyPath: a.propertyPath, count: 0 }) - 1]), map.get(a.path).count++, r))(new Map),
    []
)

console.log(result)
```

It produces this:
```
[
  {
    name: 'carousel',
    path: '/content/themecleanflex/pages/library/carousel',
    propertyName: 'imagepath',
    propertyPath: '/content/themecleanflex/pages/library/carousel/jcr:content/container22/carousel9/slides/c6',
    count: 1
  },
  {
    name: 'sample-owl',
    path: '/content/themecleanflex/pages/library/carousel/sample-owl',
    propertyName: 'imagepath',
    propertyPath: '/content/themecleanflex/pages/library/carousel/sample-owl/jcr:content/container175/carousel6/slides/c3',
    count: 2
  }
]
```

Please let me know if I am way off.

2020-06-05 16:09 UTC, smcgrath0 commented
No review comments, added count ui element
<img width="481" alt="Screen Shot 2020-06-05 at 9 08 50 AM" src="https://user-images.githubusercontent.com/49845255/83898750-2f1b8400-a70c-11ea-8e09-049dbe2e89ea.png">

2020-06-05 16:31 UTC, GastonGonzalez requested changes

2020-06-05 16:31 UTC, GastonGonzalez commented on admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
> +        return trimmedReferences;
@smcgrath0  - you never use trimmedReference. Why not just use `return this.trimReferences....`?

2020-06-05 16:31 UTC, GastonGonzalez commented on admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
> +        return result;
Same comment as above, @smcgrath0 . get rid of `let result`. You simple use return on referenceLIst.reduc...

2020-06-05 16:31 UTC, GastonGonzalez commented on admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
> +        return trimmedReferences;
This is var is unused. Just call return.

2020-06-05 16:32 UTC, GastonGonzalez requested changes
Please update all changes.

2020-06-05 16:53 UTC, GastonGonzalez approved these changes

2020-06-05 17:13 UTC, merged