Fix for: Copy/Paste works incorrectly
headwirecom/peregrine-cms pull request #704
Opened 2021-01-12 15:31 UTC by reggie7

Fix for #702

2021-01-12 22:04 UTC, ehdatheadwire approved these changes
Checked locally against develop-sling12 and confirmed that the fix/changes have been made. Looks good!

![Screen Shot 2021-01-12 at 2 03 49 PM](https://user-images.githubusercontent.com/51373617/104379926-0861cf00-54df-11eb-95de-8eedc5639463.png)

2021-01-21 14:43 UTC, Felix-Puetz requested changes
![image](https://user-images.githubusercontent.com/50131232/105365968-1ad6b980-5bff-11eb-90ab-6ee1f9562b82.png)
![image](https://user-images.githubusercontent.com/50131232/105366259-6ab58080-5bff-11eb-8094-448937d1d92b.png)

2021-01-21 14:43 UTC, Felix-Puetz commented on admin-base/ui.apps/src/main/js/apiImpl.js
>      let formData = new FormData();
if you are already removing semicolons remove this one too :D

2021-01-21 14:48 UTC, Felix-Puetz approved these changes

2021-01-21 14:49 UTC, Felix-Puetz approved these changes
![image](https://user-images.githubusercontent.com/50131232/105365968-1ad6b980-5bff-11eb-90ab-6ee1f9562b82.png)
![image](https://user-images.githubusercontent.com/50131232/105366259-6ab58080-5bff-11eb-8094-448937d1d92b.png)
![image](https://user-images.githubusercontent.com/50131232/105367652-f5e34600-5c00-11eb-8703-ff3a658e061f.png)
[Test coverage](https://github.com/Felix-Puetz/pcms-testing/commit/84943454838e829e67348d09b635bd7dccbe9444) added

2021-01-21 17:45 UTC, merged

2021-01-21 17:48 UTC, Felix-Puetz commented
Build of develop-sling12 after merge successful
![image](https://user-images.githubusercontent.com/50131232/105390388-46669d80-5c19-11eb-90e5-f92359359aa6.png)