Issues/707 - move peregrine build out of docker to prevent travis failures
headwirecom/peregrine-cms pull request #708
Opened 2021-01-13 14:49 UTC by reusr1

2021-02-04 18:42 UTC, cmrockwell commented on docker/scripts/install-peregrine.sh
> +  /themeclean-flex/themecleanflex.ui.apps-1.0-SNAPSHOT.zip \
`external-1.0-SNAPSHOT.zip` is gone from develop-sling12

2021-02-04 18:47 UTC, cmrockwell commented on platform/auth/pom.xml
>              <artifactId>commons-lang</artifactId>
Sling12 doesn't provide `commons-lang` and it's replaced with `commons-lang3`

2021-02-04 19:10 UTC, cmrockwell commented
when I run ./builddocker.sh from `develop-sling12` it takes a while but eventually completes successfully.

I checked out this PR
`git fetch upstream pull/708/head && git checkout FETCH_HEAD`
ran ./builddocker.sh

It errors at step 11/14
<img width="826" alt="Screen Shot 2021-02-04 at 1 56 17 PM" src="https://user-images.githubusercontent.com/1811207/106942899-b5042a80-66f2-11eb-9ac2-e60d47d4a1e9.png">

2021-02-04 21:43 UTC, cmrockwell requested changes
I recommend closing this PR without merging, because after this change docker will only build images using the published packages (i.e. the headwire vagrant develop / Sling9). Docker wouldn't be useful for develop-sling12 PR's going forward.

2021-02-04 22:30 UTC, reusr1 commented
> I recommend closing this PR without merging, because after this change docker will only build images using the published packages (i.e. the headwire vagrant develop / Sling9). Docker wouldn't be useful for develop-sling12 PR's going forward.

@cmrockwell not sure if that is actually true - it looks like you have to first run the travis build script before doing the docker buildscript - in the process of trying to validate this as well

2021-02-05 15:24 UTC, cmrockwell commented
> > I recommend closing this PR without merging, because after this change docker will only build images using the published packages (i.e. the headwire vagrant develop / Sling9). Docker wouldn't be useful for develop-sling12 PR's going forward.
> 
> @cmrockwell not sure if that is actually true - it looks like you have to first run the travis build script before doing the docker buildscript - in the process of trying to validate this as well

Ah ok. In that case the README.md should be updated. See commit 5a7ef3c

2021-02-05 15:32 UTC, cmrockwell commented
I'm not sure whether including the `platform/auth` commons-lang change was a mistake or what, but the build fails. Auth is not included as module of platform, so it needs to be built separately. 

<img width="1269" alt="Screen Shot 2021-02-05 at 10 29 23 AM" src="https://user-images.githubusercontent.com/1811207/107053787-3e703700-679d-11eb-9c43-27ba442a4091.png">

2021-02-05 22:06 UTC, reusr1 commented
> > > I recommend closing this PR without merging, because after this change docker will only build images using the published packages (i.e. the headwire vagrant develop / Sling9). Docker wouldn't be useful for develop-sling12 PR's going forward.
> > 
> > 
> > @cmrockwell not sure if that is actually true - it looks like you have to first run the travis build script before doing the docker buildscript - in the process of trying to validate this as well
> 
> Ah ok. In that case the README.md should be updated. See commit [3ab82ed](https://github.com/headwirecom/peregrine-cms/commit/3ab82ed7fbf46bb47d2428664e37677c6bf30dbb)

thank you for updating the readme!

2021-02-05 23:00 UTC, cmrockwell approved these changes

2021-02-13 16:48 UTC, reusr1 commented
I made a lot of changes to this branch after @GastonGonzalez wrote it and @cmrockwell reviewed it. Would be good to open this up for review again, what do you guys think?

2021-02-18 23:24 UTC, cmrockwell commented
> I made a lot of changes to this branch after @GastonGonzalez wrote it and @cmrockwell reviewed it. Would be good to open this up for review again, what do you guys think?
> 
> we reduced the travis build time for peregrine from 12 minutes to 8 minutes and the docker image size from 2GB to 800MB

Looks good! Just added one more thing to the readme  7f506da7d560d0f780fa26effd705e0e119100a4

2021-02-19 12:45 UTC, merged