some basic docker usage
headwirecom/peregrine-cms pull request #744
Opened 2021-02-14 15:52 UTC by reusr1

some hints about how to use docker

2021-02-16 16:00 UTC, GastonGonzalez requested changes
Please add Docker remove commands to allow testing new branches.

2021-02-17 20:26 UTC, reggie7 approved these changes

2021-03-24 19:25 UTC, reusr1 commented
> Please add Docker remove commands to allow testing new branches.

@GastonGonzalez I added the docker remove with -rm to the run command. I added a bit of explanation to each command to ease people without a lot of docker knowledge into it a bit more.

2021-03-24 23:49 UTC, ehdatheadwire commented on docs/public/docker/index.md
> +docker run -it -p 8080:8080 peregrinecms/peregrinecms:pr-{number}
Don't we also have to replace 8080 with a made-up number that is greater than 9000? e.g. 9209 for pr-209?

2021-03-25 22:13 UTC, ehdatheadwire commented
replace all instances of /peregrinecms with /peregrine-cms -- through testing the new instructions I discovered that this missing dash is what was causing my error messages while testing a pr yesterday :)

2021-03-25 23:13 UTC, ehdatheadwire approved these changes
Recommended adjustments made. Looks good from this view!

2021-03-25 23:17 UTC, GastonGonzalez approved these changes

2021-03-25 23:17 UTC, merged